#!/usr/bin/env bash

LAMTRAM_DIR="$(dirname $(dirname $(readlink -f $0)))"

REPOSITORY="$(cat $(dirname $0)/config)"

# Use image name from "config", use Dockerfile in this directory, use lamtram
# root as context root

# Dependencies are versioned, so they can be cached.  Lamtram is not versioned,
# so make sure to always update to current version on build.
nvidia-docker build -t $REPOSITORY-deps -f $LAMTRAM_DIR/docker/Dockerfile.lamtram-deps $LAMTRAM_DIR
nvidia-docker build --no-cache -t $REPOSITORY -f $LAMTRAM_DIR/docker/Dockerfile.lamtram $LAMTRAM_DIR
